/**
 * InviteConfig — the single serialization contract between editor and invite page.
 * Packed as JSON -> deflate -> base64url in the URL hash (`#p=<payload>`).
 * Changing any field shape requires bumping `v` and a migration path in codec.ts.
 */

export type GagModeId = 'dodge' | 'fakeErrors' | 'fakeLoad' | 'shrink' | 'confirmLoop';

export interface ThemeConfig {
  /** id of a built-in preset (editor renders swatch cards from THEME_PRESETS) */
  presetId: string;
  /** page background color, css color string */
  bg: string;
  /** accent (buttons / highlights), css color string */
  accent: string;
  /** main text color, css color string */
  textColor: string;
  /** global font scale multiplier, clamped 0.85–1.3 */
  fontScale: number;
  /** decorative emojis scattered on the background */
  emojiDecor: string[];
}

export interface IntroConfig {
  title: string;
  subtitle: string;
  cta: string;
}

export interface QuestionConfig {
  text: string;
  agreeLabel: string;
  disagreeLabel: string;
}

export interface DodgeCfg {
  /** number of dodges before falling through to the next mode; min 1 */
  times: number;
}

export interface FakeErrorsCfg {
  /** cycled in order, one per press */
  messages: string[];
}

export interface FakeLoadCfg {
  /** spinner duration per press */
  delayMs: number;
  /** failure text shown after the spinner */
  failText: string;
}

export interface ShrinkCfg {
  /** agree button shrinks toward this scale and stops (never disappears) */
  minScale: number;
}

export interface ConfirmLoopCfg {
  /** confirmation prompts chained forever: last one wraps to first */
  prompts: string[];
}

export interface MilestonesCfg {
  /** every N presses, surface the next milestone message (cycled) */
  everyN: number;
  messages: string[];
}

export interface GagConfig {
  /** applied in order, cycling forever; agree NEVER succeeds */
  modes: GagModeId[];
  dodge: DodgeCfg;
  errors: FakeErrorsCfg;
  fakeLoad: FakeLoadCfg;
  shrink: ShrinkCfg;
  confirmLoop: ConfirmLoopCfg;
  milestones: MilestonesCfg;
}

export interface DisagreeStep {
  text: string;
  buttonLabel: string;
}

export interface DisagreeFlowConfig {
  steps: DisagreeStep[];
  /** when true, last step wraps back to the first instead of reaching final */
  loop: boolean;
  finalTitle: string;
  finalText: string;
}

export interface NotifyConfig {
  enabled: boolean;
  /** ntfy topic; generated by editor as crypto.randomUUID(); null = notifications off */
  topic: string | null;
}

export interface InviteConfig {
  v: 1;
  theme: ThemeConfig;
  intro: IntroConfig;
  question: QuestionConfig;
  gag: GagConfig;
  disagreeFlow: DisagreeFlowConfig;
  notify: NotifyConfig;
}
